[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$wniP0fqfEyKkdE6pdW5NCQ$knvJ22r1fj358rRymhJP02.ZoDtRwk4sm.scPKc8TQoBouUuBeScIij9yai8D8HJFh9mfwiDwRNrqNSwzapjxQ

